#include <iostream>
#include "gtest/gtest.h"
#include "test_fasta.hpp"

namespace {

class U3010 : public TestFasta {
protected:
    U3010() {
        IFNAME1 = (char *) "mir_001.fasta";
        IFNAME2 = (char *) "utr3_010.fasta";
    }
};

TEST_F(U3010, mrna_fasta) {
    read_files();
    mrna_ids = coreInput.get_mrna_ids();
    mrna_seqs = coreInput.get_mrna_seqs();

    EXPECT_EQ(1u, length(mrna_ids));

    const char *id1 = "hg18_refGene NM_004339 range=chr21:45093941-45095923 5'pad=0 3'pad=0 "
            "revComp=TRUE strand=- repeatMasking=none";
    EXPECT_STREQ(id1, seqan::toCString(mrna_ids[0]));

    EXPECT_EQ(1u, length(mrna_seqs));
    const char *seq1 = "AGCGCUCCAGCACAUCAGUCCCGACGCUUCCUGUGAGGUGCACGCUCCGC"
            "AGCCCAGCCCAGCCGGGAGACCACGUGGCCAUUGCGGUCUCCUGACCUUG"
            "GCCAGUGAACCUGCCAGCCUUCCAGGACAGGCGGCCGGAGAGCUGCCCCU"
            "GAAGGACAGUCCUCUCGUCUUGCAGACUGGUGACCUUCUAUUCCCUGUUC"
            "AUCUCUGUUUCUAGAUUUAGUCACUUGAAAUAAGAAAUCUUUGGGGUUUG"
            "GGCUUUUUUAUACUCUUCUCAGUUUGUGAAACGCUAACUGCACACGAAGC"
            "CGCCUGACGGCACCCAGCGCUGUGGCUGUCAUUCUCCCAGGGCAGAACCC"
            "UGCGUUUCUCUCUGUCCACUAACAAGCUUCACACGCAACACAGGGAAGUC"
            "GGUUUGACUUUUGUCAUGAGGAGAACUGACCAGCCCUCAUCAUUCCCCAU"
            "AAAACCACGGACAGCGUCUGUGUGCGCAUCUUGAGUCUUCACACCUGUUG"
            "ACUCACACGGCUUUUGCUGAUGACACGGGGCUCCAGUACACAGUCUGAUA"
            "AGGACUUAACGUCCUAACCUCAAUUGUAUUAAAUAGCAUUGGGGAAUAGC"
            "UAAACCUUUUUAAAAAAAUUUAUUGGAUUUUCCUCCCUGCUUAAAAGAUU"
            "UCACCAGAAAACCUUCAUAUAAAAAUUCAGGCCCUUUUUGGACAAUUUUU"
            "AAAAUUUGUAUCUUUACUAGAACAUGAGAAUCUUUUUCCCUUGGAAGCUU"
            "GAAUUAUAAAUGUGGUGUUUGGCCUGCCUCAGCAGCACCAGUUGACUGCU"
            "CGUGUGCCAGCGGUGUGGGGAGGACGGGGCAGGACGCUGCAGCUCUCUCC"
            "AGCCCUGUUGGCAUCCUCAGUGCCUGCAGGCCUCUCGCUGCCUGUUGGGC"
            "UGUCUGGGGGGUGGCCAUUUAGGGAUCGUGGGGACGGGGUCCACCCCAAG"
            "AAGAAAGAAAGGCCCGUCCACAGGCCCGGCUCUGGGCCACGUGCCCCGGA"
            "AGCAGGUGUGUCCAGAGUCAGCUGAGGGCUCUCCCCACACCACCCAGCAG"
            "GCGCUGGUGCUCCUUCUGCCUCAUGGGACCAGUCCAGCUUCCAGCCGCUC"
            "UGGCUCGAGGGUGGUCUGACCACUUCCUUCUGAGUGGGCUUCUCUGGGAG"
            "CUCUCCAGUGGCACUGCUGGACCUGCCCACGUUUCUGUAAAAUCAGGAUA"
            "CGUGGCUUUAGUAAGCAGACCAAGCGCUUCGUGGCAGGGAAAGCAGCGUG"
            "CGGGGAAGUCACUGAAAAGUGCUGCCUAAGGAAGUUUGGAAAUAGUCCCU"
            "GUUCCAGAUUGCCUUGAAUUUUAAAACAUUUUGCUUUGGGAAAGUAGGUC"
            "AGCAGCACCUAAGAUCAAGGAUGCGUUCCAUUUUCACACUUCACAGUCAU"
            "GAAAACUGAGAAGACUGUCUUCAGCGUGAACUAAAGUUCACAGGCAGAUC"
            "ACUGAUCCAGAACACUUCAAGAACUCGUCAAACAGCUCGAUAAGCCUUUU"
            "UGACUGUGUACAUCUGUACCGGGAAUAACAUUCCUAGGCUGAAAUUUCCA"
            "CAAAGAAUAGAACCUGUACCCAGUUCUUCAGGCUGAUUUCCCUGACCUCU"
            "UGGGCAUUUGUAUUUGUAGUAAAGUAUUGCAGAGAUUCCUAAGUAUUUUA"
            "UAGCAGCCAUCAAAAUUGGACUUUGUAUUGUUUAUUCAUAAAAGACACUU"
            "GGUAAUAGACUUCAGUGAACUCUGUAUGAAUGCAGUAGUGUGUGUGCAAA"
            "AUCCGCUUCCUGAGCGUAGGGUGCUGAGCUGGCGCUAGGGCUCGGUUGUG"
            "AAAUACAGCGUAGUCAGCCCUUGCGCUCAGUGUAGAAACCCACGUCUGUA"
            "AGGUCGGUCUUCGUCCAUCUGCUUUUUUCUGAAAUACACUAAGAGCAGCC"
            "ACAAAACUGUAACCUCAAGGAAACCAUAAAGCUUGGAGUGCCUUAAUUUU"
            "UAACCAGUUUCCAAUAAAACGGUUUACUACCUG";
    EXPECT_STREQ(seq1, seqan::toCString((seqan::CharString) mrna_seqs[0]));
}
}
