#include<string>
#include <seqan/sequence.h>
#include "gtest/gtest.h"
#include "test_mkens.hpp"

namespace {

class Site04MMGU2 : public TestSiteMKENS {
protected:
    Site04MMGU2() {
        IFNAME1 = (char *) "mir_001.fasta";
        IFNAME2 = (char *) "ts_04_mmgu_2.fasta";
    }

};

TEST_F(Site04MMGU2, mir1) {
    read_and_set_seqs();
    TIdx index(mrna_seqs);
    TFin finder(index);
    mkens::MKECore mkCore(mOpts, mirna_ids, mirna_seqs, mrna_ids, mrna_seqs, index, finder);
    mkCore.find_seed_sites(1);
    TSit &sites = mkCore.get_seed_sites();

    EXPECT_EQ(190u, sites.get_length());

    test_sites(sites, 0, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 0, 20, true, 0);
    test_sites(sites, 1, "mr:7mer_GUM,pt:6mer,rh:7mer_GUM,tm:6mer,ts:NA,sv:6mer", 0, 30, true, 0);
    test_sites(sites, 2, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 1, 20, true, 0);
    test_sites(sites, 3, "mr:7mer_GUM,pt:6mer,rh:7mer_GUM,tm:7mer-A1,ts:7mer-A1,sv:7mer-A1", 1, 30, true, 0);
    test_sites(sites, 4, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 2, 20, true, 0);
    test_sites(sites, 5, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 2, 30, true, 0);
    test_sites(sites, 6, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 3, 20, true, 0);
    test_sites(sites, 7, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 3, 30, true, 0);
    test_sites(sites, 8, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 4, 20, true, 0);
    test_sites(sites, 9, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:7mer-m8,ts:NA,sv:NA", 4, 30, true, 0);
    test_sites(sites, 10, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 5, 20, true, 0);
    test_sites(sites, 11, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:8mer,ts:NA,sv:GUM", 5, 30, true, 0);
    test_sites(sites, 12, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 6, 20, true, 0);
    test_sites(sites, 13, "mr:7mer_BT,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 6, 29, true, 0);
    test_sites(sites, 14, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 6, 30, true, 0);
    test_sites(sites, 15, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 7, 20, true, 0);
    test_sites(sites, 16, "mr:7mer_BT,pt:NA,rh:NA,tm:NA,ts:NA,sv:BT", 7, 29, true, 0);
    test_sites(sites, 17, "mr:7mer_MMGU,pt:NA,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 7, 30, true, 0);
    test_sites(sites, 18, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 8, 20, true, 0);
    test_sites(sites, 19, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 8, 30, true, 0);
    test_sites(sites, 20, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 9, 20, true, 0);
    test_sites(sites, 21, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 9, 30, true, 0);
    test_sites(sites, 22, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 10, 20, true, 0);
    test_sites(sites, 23, "mr:7mer_GUM,pt:7mer_GUM,rh:7mer_GUM,tm:7mer-m8,ts:NA,sv:NA", 10, 30, true, 0);
    test_sites(sites, 24, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 11, 20, true, 0);
    test_sites(sites, 25, "mr:7mer_GUM,pt:7mer_GUM,rh:7mer_GUM,tm:8mer,ts:NA,sv:GUT", 11, 30, true, 0);
    test_sites(sites, 26, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 12, 20, true, 0);
    test_sites(sites, 27, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 12, 30, true, 0);
    test_sites(sites, 28, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 13, 20, true, 0);
    test_sites(sites, 29, "mr:7mer_MMGU,pt:NA,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 13, 30, true, 0);
    test_sites(sites, 30, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 14, 20, true, 0);
    test_sites(sites, 31, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 14, 30, true, 0);
    test_sites(sites, 32, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 15, 20, true, 0);
    test_sites(sites, 33, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 15, 30, true, 0);
    test_sites(sites, 34, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 16, 20, true, 0);
    test_sites(sites, 35, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:7mer-m8,ts:NA,sv:BT", 16, 30, true, 0);
    test_sites(sites, 36, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 17, 20, true, 0);
    test_sites(sites, 37, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:8mer,ts:NA,sv:GUM", 17, 30, true, 0);
    test_sites(sites, 38, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 18, 20, true, 0);
    test_sites(sites, 39, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 18, 30, true, 0);
    test_sites(sites, 40, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 19, 20, true, 0);
    test_sites(sites, 41, "mr:7mer_MMGU,pt:NA,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 19, 30, true, 0);
    test_sites(sites, 42, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 20, 20, true, 0);
    test_sites(sites, 43, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 20, 30, true, 0);
    test_sites(sites, 44, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 21, 20, true, 0);
    test_sites(sites, 45, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 21, 30, true, 0);
    test_sites(sites, 46, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 22, 20, true, 0);
    test_sites(sites, 47, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:7mer-m8,ts:NA,sv:BT", 22, 30, true, 0);
    test_sites(sites, 48, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 23, 20, true, 0);
    test_sites(sites, 49, "mr:7mer_GUT,pt:7mer_GUT,rh:7mer_GUT,tm:8mer,ts:NA,sv:GUM", 23, 30, true, 0);
    test_sites(sites, 50, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 24, 20, true, 0);
    test_sites(sites, 51, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 24, 30, true, 0);
    test_sites(sites, 52, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 25, 20, true, 0);
    test_sites(sites, 53, "mr:7mer_MMGU,pt:NA,rh:NA,tm:7mer-A1,ts:NA,sv:NA", 25, 30, true, 0);
    test_sites(sites, 54, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 26, 20, true, 0);
    test_sites(sites, 55, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 26, 30, true, 0);
    test_sites(sites, 56, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 27, 20, true, 0);
    test_sites(sites, 57, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:BM", 27, 30, true, 0);
    test_sites(sites, 58, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 28, 20, true, 0);
    test_sites(sites, 59, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 28, 30, true, 0);
    test_sites(sites, 60, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 29, 20, true, 0);
    test_sites(sites, 61, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 29, 30, true, 0);
    test_sites(sites, 62, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 30, 20, true, 0);
    test_sites(sites, 63, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 30, 30, true, 0);
    test_sites(sites, 64, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 31, 20, true, 0);
    test_sites(sites, 65, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 31, 30, true, 0);
    test_sites(sites, 66, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 32, 20, true, 0);
    test_sites(sites, 67, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 32, 30, true, 0);
    test_sites(sites, 68, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 33, 20, true, 0);
    test_sites(sites, 69, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 33, 30, true, 0);
    test_sites(sites, 70, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 34, 20, true, 0);
    test_sites(sites, 71, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 34, 30, true, 0);
    test_sites(sites, 72, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 35, 20, true, 0);
    test_sites(sites, 73, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 35, 30, true, 0);
    test_sites(sites, 74, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 36, 20, true, 0);
    test_sites(sites, 75, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 36, 30, true, 0);
    test_sites(sites, 76, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 37, 20, true, 0);
    test_sites(sites, 77, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 37, 30, true, 0);
    test_sites(sites, 78, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 38, 20, true, 0);
    test_sites(sites, 79, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 38, 30, true, 0);
    test_sites(sites, 80, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 39, 20, true, 0);
    test_sites(sites, 81, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 39, 30, true, 0);
    test_sites(sites, 82, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 40, 20, true, 0);
    test_sites(sites, 83, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 40, 30, true, 0);
    test_sites(sites, 84, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 41, 20, true, 0);
    test_sites(sites, 85, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 41, 30, true, 0);
    test_sites(sites, 86, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 42, 20, true, 0);
    test_sites(sites, 87, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 42, 30, true, 0);
    test_sites(sites, 88, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 43, 20, true, 0);
    test_sites(sites, 89, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 43, 30, true, 0);
    test_sites(sites, 90, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 44, 20, true, 0);
    test_sites(sites, 91, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 44, 30, true, 0);
    test_sites(sites, 92, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 45, 20, true, 0);
    test_sites(sites, 93, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 45, 30, true, 0);
    test_sites(sites, 94, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 46, 20, true, 0);
    test_sites(sites, 95, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 46, 30, true, 0);
    test_sites(sites, 96, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 47, 20, true, 0);
    test_sites(sites, 97, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 47, 30, true, 0);
    test_sites(sites, 98, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 48, 20, true, 0);
    test_sites(sites, 99, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 48, 30, true, 0);
    test_sites(sites, 100, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 49, 20, true, 0);
    test_sites(sites, 101, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 49, 30, true, 0);
    test_sites(sites, 102, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 50, 20, true, 0);
    test_sites(sites, 103, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 50, 30, true, 0);
    test_sites(sites, 104, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 51, 20, true, 0);
    test_sites(sites, 105, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 51, 30, true, 0);
    test_sites(sites, 106, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 52, 20, true, 0);
    test_sites(sites, 107, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 52, 30, true, 0);
    test_sites(sites, 108, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 53, 20, true, 0);
    test_sites(sites, 109, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 53, 30, true, 0);
    test_sites(sites, 110, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 54, 20, true, 0);
    test_sites(sites, 111, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 54, 30, true, 0);
    test_sites(sites, 112, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 55, 20, true, 0);
    test_sites(sites, 113, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 55, 30, true, 0);
    test_sites(sites, 114, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 56, 20, true, 0);
    test_sites(sites, 115, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 56, 30, true, 0);
    test_sites(sites, 116, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 57, 20, true, 0);
    test_sites(sites, 117, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 57, 30, true, 0);
    test_sites(sites, 118, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 58, 20, true, 0);
    test_sites(sites, 119, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 58, 30, true, 0);
    test_sites(sites, 120, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 59, 20, true, 0);
    test_sites(sites, 121, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 59, 30, true, 0);
    test_sites(sites, 122, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 60, 20, true, 0);
    test_sites(sites, 123, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 60, 30, true, 0);
    test_sites(sites, 124, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 61, 20, true, 0);
    test_sites(sites, 125, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 61, 30, true, 0);
    test_sites(sites, 126, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 62, 20, true, 0);
    test_sites(sites, 127, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 62, 30, true, 0);
    test_sites(sites, 128, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 63, 20, true, 0);
    test_sites(sites, 129, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 63, 30, true, 0);
    test_sites(sites, 130, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 64, 20, true, 0);
    test_sites(sites, 131, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 64, 30, true, 0);
    test_sites(sites, 132, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 65, 20, true, 0);
    test_sites(sites, 133, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 65, 30, true, 0);
    test_sites(sites, 134, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 66, 20, true, 0);
    test_sites(sites, 135, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 66, 30, true, 0);
    test_sites(sites, 136, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 67, 20, true, 0);
    test_sites(sites, 137, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 67, 30, true, 0);
    test_sites(sites, 138, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 68, 20, true, 0);
    test_sites(sites, 139, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 68, 30, true, 0);
    test_sites(sites, 140, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 69, 20, true, 0);
    test_sites(sites, 141, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 69, 30, true, 0);
    test_sites(sites, 142, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 70, 20, true, 0);
    test_sites(sites, 143, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 70, 30, true, 0);
    test_sites(sites, 144, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 71, 20, true, 0);
    test_sites(sites, 145, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 71, 30, true, 0);
    test_sites(sites, 146, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 72, 20, true, 0);
    test_sites(sites, 147, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 72, 30, true, 0);
    test_sites(sites, 148, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 73, 20, true, 0);
    test_sites(sites, 149, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 73, 30, true, 0);
    test_sites(sites, 150, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 74, 20, true, 0);
    test_sites(sites, 151, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 74, 30, true, 0);
    test_sites(sites, 152, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 75, 20, true, 0);
    test_sites(sites, 153, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 75, 30, true, 0);
    test_sites(sites, 154, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 76, 20, true, 0);
    test_sites(sites, 155, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 76, 30, true, 0);
    test_sites(sites, 156, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 77, 20, true, 0);
    test_sites(sites, 157, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 77, 30, true, 0);
    test_sites(sites, 158, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 78, 20, true, 0);
    test_sites(sites, 159, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 78, 30, true, 0);
    test_sites(sites, 160, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 79, 20, true, 0);
    test_sites(sites, 161, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 79, 30, true, 0);
    test_sites(sites, 162, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 80, 20, true, 0);
    test_sites(sites, 163, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 80, 30, true, 0);
    test_sites(sites, 164, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 81, 20, true, 0);
    test_sites(sites, 165, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 81, 30, true, 0);
    test_sites(sites, 166, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 82, 20, true, 0);
    test_sites(sites, 167, "mr:8mer_BT,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:BT", 82, 30, true, 0);
    test_sites(sites, 168, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 83, 20, true, 0);
    test_sites(sites, 169, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 83, 30, true, 0);
    test_sites(sites, 170, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 84, 20, true, 0);
    test_sites(sites, 171, "mr:7mer_BT,pt:NA,rh:NA,tm:NA,ts:NA,sv:BT", 84, 30, true, 0);
    test_sites(sites, 172, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 85, 20, true, 0);
    test_sites(sites, 173, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 85, 30, true, 0);
    test_sites(sites, 174, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 86, 20, true, 0);
    test_sites(sites, 175, "mr:8mer_BT,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:BT", 86, 30, true, 0);
    test_sites(sites, 176, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 87, 20, true, 0);
    test_sites(sites, 177, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:NA,ts:NA,sv:NA", 87, 30, true, 0);
    test_sites(sites, 178, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 88, 20, true, 0);
    test_sites(sites, 179, "mr:7mer_BT,pt:NA,rh:NA,tm:NA,ts:NA,sv:BT", 88, 30, true, 0);
    test_sites(sites, 180, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 89, 20, true, 0);
    test_sites(sites, 181, "mr:7mer_MMGU,pt:NA,rh:NA,tm:NA,ts:NA,sv:NA", 89, 30, true, 0);
    test_sites(sites, 182, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 90, 20, true, 0);
    test_sites(sites, 183, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 90, 30, true, 0);
    test_sites(sites, 184, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 91, 20, true, 0);
    test_sites(sites, 185, "mr:8mer_MMGU,pt:8mer_MMGU,rh:NA,tm:6mer,ts:NA,sv:NA", 91, 30, true, 0);
    test_sites(sites, 186, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 92, 20, true, 0);
    test_sites(sites, 187, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 92, 30, true, 0);
    test_sites(sites, 188, "mr:7mer_GU+,pt:NA,rh:7mer_GUT,tm:NA,ts:NA,sv:NA", 93, 20, true, 0);
    test_sites(sites, 189, "mr:7mer_MMGU,pt:NA,rh:NA,tm:6mer,ts:NA,sv:NA", 93, 30, true, 0);

}
}
